# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapoint',
            old_name='count',
            new_name='uSv',
        ),
    ]
