# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graas', '0002_auto_20161015_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='uSv',
            field=models.FloatField(),
        ),
    ]
